### ISSUE TITLE
C# SDK postdata is missing field `extraData`

### ISSUE THREAD

**Issue by trinvh** [momo-wallet/payment#12]
**Describe the bug**
Within C# SDK:
- Hardcoded value of *Secret Key*.
- Missing JSON post fields.

**To Reproduce**
Following the C# SDK, you will see the JObject `message` is missing `extraData` property that will lead to "Invalid signature" error.

**Expected behavior**
The C# SDK should be updated with correct example

**Additional context**
There are some uncommon rules with the signature generator. All params should be sorted in alphabet order, that will help developer easier in debugging

**Comment by thucuyenn** [comment]
hi trinvh,
Thanks for your feedback. 
We'll record your idea
And C# example'll fix soonest
