### ISSUE TITLE
[golang] Generate RSA hash string - giải mã hash thất bại

### ISSUE THREAD

**Issue by namhq1989** [momo-wallet/payment#3]
**Describe the bug**
Xử lý thanh toán App-In-App, gọi `POST https://test-payment.momo.vn/pay/app` để kiểm tra transaction.

Sử dụng code mẫu generate RSA string ở https://github.com/momo-wallet/payment/blob/master/golang/src/MoMo/MoMo.go

Thay pubkey bằng key ở business.momo.vn

Nhận được về lỗi
`{"status":153,"message":"Giải mã hash thất bại"}`

**Expected behavior**
Check transaction thành công

**Screenshots**
![Screen Shot 2019-05-02 at 11 19 32 AM](https://user-images.githubusercontent.com/1388374/57056369-48adf900-6ccc-11e9-9c66-8ece8f7eb416.png)

![Screen Shot 2019-05-02 at 11 19 58 AM](https://user-images.githubusercontent.com/1388374/57056373-506d9d80-6ccc-11e9-9b2a-d97ff3684175.png)

**Comment by caokhang91** [comment]
Hello bạn,
Bạn chuyển hàm encrypt dùng ``rsa.EncryptOAEP()`` sang ``rsa.EncryptPKCS1v15()`` giúp mình nhé

`
//2. TODO - Encrypt PKCS1V15 RSA encryption using `publicKey` in memory
randomReader := rand.Reader
ciphertext, err := rsa.EncryptPKCS1v15(randomReader, publicKey, rawJashJson)
`
Thank you!

**Comment by danhtran12797** [comment]
Hello mình cũng gặp vấn đề đó, nhưng mình code trên Android.
Đây là đoạn code mẫu mình lấy trên [github](https://github.com/momo-wallet/java/blob/master/src/main/java/com/mservice/pay/processor/notallinone/AppPay.j) để lấy hashRSA, public key mình lấy ở business.momo.vn
![image](https://user-images.githubusercontent.com/48312687/77453049-4cd58e80-6e29-11ea-89c6-07a0170aa51b.png)
Mong a giải đáp thắc mắc.
Cảm ơn.

**Comment by tomnk** [comment]
@caokhang91 I also get this error when I do payment. Can you help me?
`static async encryptRSA(data) {
    const publicKey = await fs.readFileSync(momoConfig.publicKeyFile, {
      encoding: 'utf8',
      flag: 'r',
    });
    console.log(publicKey);
    const key = new NodeRSA(publicKey, { encryptionScheme: 'pkcs1' });
    const encryptData = key.encrypt(JSON.stringify(data), 'base64');

    return encryptData.toString('base64');
  }`
