### ISSUE TITLE
Momo responds with bad format request: invalid signature

### ISSUE THREAD

**Issue by zamin0411** [momo-wallet/payment#38]
![image](https://user-images.githubusercontent.com/86704819/216809779-d5aac231-22a5-40e5-9dfd-edd2b45f5873.png)
I tried to run the golang src code but I received this response. Please help me

**Comment by tojinguyen** [comment]
How to fix this error, can you share with me bro

**Comment by zamin0411** [comment]
@tojinguyen 
It's been a long time, so I can't remember exactly, but I think the credentials in the example didn't work. I ended up creating my own MoMo test account.
