### ISSUE TITLE
On Localhost server --- fatal error displayed

### ISSUE THREAD

**Issue by ankundaracheal** [momo-wallet/payment#5]
> 

> ### ****Describe** the bug**

A calll to an undefined function curl_int() on MOMO.php on line 5

**To Reproduce**
1. copy and paste the php folder among the projects of wamp/www
2. open the project(PHP) from the browser .ie localhost
3. click MOMO.php

**Expected behavior**
SEE THE INTERFACE.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/48234283/58454539-751c3000-8127-11e9-9471-be4aa524ce6f.PNG)

**Desktop (please complete the following information):**
 - OS:WINDOWS7
 - BrowserMOZILLA
 - Version NOT SURE

**Additional context**
programs with the function curl_int() normally dont run on my wamp. i am using wampserver **2.1**

**Comment by caokhang91** [comment]
Hello guy,

Just execute php file by command and uncomment ``extension=php_curl.dll`` lib in ``php.ini`` and type

``php Momo.php``
